# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
- script: pip install pandas
- script: pip install openpyxl
- script: pip install -q -U google-generativeai
- script: pip install requests

  displayName: 'Run a one-line script'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'single.py'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
